### ISSUE TITLE
Enabling TLS has errors in logs

### ISSUE THREAD

**Issue by zaphinath** [dragonflydb/dragonfly-operator#145]
We have the dragonfly operator running in a k8 cluster and we have an implementation with TLS enabled. We have a Certificate resource that generated a self signed cert according to the docs you have, which then puts it into a secret and it gets slurped up. We are able to connect to the dragonfly instance and set values and get values with it, however, when I look at the dragonfly logs they are full of errors about SSL connections. I am wondering if we could get a little more insight into what is causing this error and why. 

dragonfly.yaml
```
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly-ssl
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly-ssl
spec:
  replicas: 1
  authentication:
    passwordFromSecret:
      name: dragonfly-password
      key: password
  tlsSecretRef:
    name: dragonfly-ssl
  serviceSpec:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: dragonfly-ssl.test.int
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  resources:
    requests:
      cpu: 1
      memory: 2000Mi
    limits:
      cpu: 2
      memory: 2200Mi #Dragonfly auto sets the memory limit internally based on this hard limit
  # Snapshot section is only needed if persistence is required. Killing stand alone pod restores last snapshot
  snapshot:
    cron: "*/5 * * * *"
    persistentVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi

```

Error in the dragonfly pod
```W20240123 15:55:55.781884 9 dragonfly_connection.cc:385] Error handshaking Software caused connection abort
W20240123 15:55:55.781948 9 dragonfly_connection.cc:385] Error handshaking Software caused connection abort
W20240123 15:55:55.781989 8 dragonfly_connection.cc:385] Error handshaking Software caused connection abort
W20240123 15:55:57.887292 9 dragonfly_connection.cc:385] Error handshaking error:1408F10B:SSL routines:ssl3_get_record:wrong version number
W20240123 15:55:57.923570 8 dragonfly_connection.cc:385] Error handshaking error:1408F10B:SSL routines:ssl3_get_record:wrong version number
W20240123 15:56:00.149127 9 dragonfly_connection.cc:385] Error handshaking Software caused connection abort
W20240123 15:56:00.149132 8 dragonfly_connection.cc:385] Error handshaking Software caused connection abort
W20240123 15:56:00.149261 9 dragonfly_connection.cc:385] Error handshaking Software caused connection abort
W20240123 15:56:00.149320 8 dragonfly_connection.cc:385] Error handshaking Software caused connection abort
W20240123 15:56:00.149365 9 dragonfly_connection.cc:385] Error handshaking Software caused connection abort
```

This error just repeats continuously filling the logs.

**Comment by zaphinath** [comment]
So digging more into this I decided to add the following field:
```
spec:
  authentication:
    clientCaCertSecret:
      name: dragonfly-ssl
      key: ca.crt
``` 
the tls secret has the tls.key, tls.crt, and ca.crt. Adding the ca.crt removed all the errors like the following from the logs:
```
W20240123 15:56:00.149365 9 dragonfly_connection.cc:385] Error handshaking Software caused connection abort
```

However, there are still these errors in the logs ```W20240123 15:55:57.887292 9 dragonfly_connection.cc:385] Error handshaking error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

Upon further investigation it looks like it has to do with the healthcheck and readiness probe. The healthcheck is just a file that is called and it looks to see if there is a TLS cert and if there is it uses that cert in it's call 
```cat /usr/local/bin/healthcheck.sh 
#!/bin/sh

HOST="localhost"
PORT=6379

# If we're running with TLS enabled, utilise OpenSSL for the check
if [ -f "/etc/dragonfly/tls/ca.crt" ]
then
    _healthcheck="openssl s_client -connect ${HOST}:${PORT} -CAfile /etc/dragonfly/tls/ca.crt -quiet -no_ign_eof"
else
    _healthcheck="nc -q1 $HOST $PORT"
fi

echo PING | ${_healthcheck}

exit $?
```
The problem lies in the path it is looking for. /etc/dragonfly/tls/ca.crt does not exist. When I added the client cert the path is ```/etc/dragonfly/client-ca-cert/ca.crt``` and the tls cert is installed in /etc/dragonfly-tls/tls.crt and /etc/dragonfly-tls/tls.key. The path for the healthcheck needs to be updated or we need the ability to mount the ca.crt to the path that the healthcheck is looking for so it uses it.
