### ISSUE TITLE
Redis Sentinel like Client Expereince

### ISSUE THREAD

**Issue by sav116** [dragonflydb/dragonfly-operator#149]
Hello, I'm very interested in your product!
I'm new to dragonflydb, but I have a need to make a high availability installation of dragonflydb on kubernetes cluster.

I installed the operator:
`kubectl apply -f https://raw.githubusercontent.com/dragonflydb/dragonfly-operator/main/manifests/dragonfly-operator.yaml`

And installed dragonflydb:
```
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  namespace: dragonfly
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly-sample
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly-sample
spec:
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.14.1
  args:
  - "--cluster_mode=emulated"
  replicas: 3
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 4
      memory: 8Gi
  serviceSpec:
    type: LoadBalancer
```

But when I check the installation by killing the master:
```
kubectl -n dragonfly get pods -l role=master
NAME                 READY   STATUS    RESTARTS   AGE
dragonfly-sample-1   1/1     Running   0          5m15s
```
```
kubectl -n dragonfly delete pod dragonfly-sample-1
pod "dragonfly-sample-1" deleted
```

After this I get an error on the client:
`redis.exceptions.ConnectionError: Error 61 connecting to dragonfly-sample:6379. Connection refused`

My python verification code looks like this:
```
import redis

import random
import string

r = redis.Redis(host='dragonfly-sample', port=6379, db=15, decode_responses=True)

def get_random_string(length):
    return ''.join(random.choice(string.ascii_letters) for i in range(length))

for i in range(0,100_000_000):
    key = get_random_string(5)
    r.set(key, get_random_string(30))
```

Dependency versions:
Kubernetes: v1.28.5
Python redis-client: 5.0.1

Please help me with the problem, maybe my installation is not correct?
The goal is to get rid of the error and increase reliability
