### ISSUE TITLE
When adding arguments there are duplicates

### ISSUE THREAD

**Issue by zaphinath** [dragonflydb/dragonfly-operator#161]
First off the dragonfly docs say that http mode is enabled by default, but when we spin up the instances through the operator it sets the argument `--primary_port_http_enabled=false.`

If I add the following block of code to enable this to true 
```
spec:
  args:
    - "--primary_port_http_enabled=true"
 ```

This then creates the following on the pod itself. The key value of the argument gets duplicated.

```
spec:
  containers:
    - args:
        - '--alsologtostderr'
        - '--primary_port_http_enabled=false'
        - '--admin_port=9999'
        - '--admin_nopass'
        - '--primary_port_http_enabled=true'
        - '--dir=/dragonfly/snapshots'
        - '--snapshot_cron=*/5 * * * *'
```

I am not sure if there is a way to remove the original, should we just set the original to true so it matches the [docs](https://www.dragonflydb.io/docs/managing-dragonfly/flags#--primary_port_http_enabled), or should we try and remove duplicates if we want to overwrite one of the default arguments?
