### ISSUE TITLE
When memcached mode is enabled port isn't automatically opened

### ISSUE THREAD

**Issue by zaphinath** [dragonflydb/dragonfly-operator#167]
When we add the args to the dragonfly.yaml like the following it doesn't open that port on the kubernetes service. The operator api doesn't appear to have the ability to custom set ports and port forwarding so not sure what the best approach is to getting the memcached port opened.

```
  spec:
    args:
    - --memcached_port=11211
```
and it produces only the following ports on the svc
```
  ports:
    - name: redis
      nodePort: 30155
      port: 6379
      protocol: TCP
      targetPort: 6379
```
