### ISSUE TITLE
Backup file cleaning

### ISSUE THREAD

**Issue by R-Loic** [dragonflydb/dragonfly-operator#179]
Using this snapshot configuration with pvc:
```
  snapshot:
    cron: "*/5 * * * *"
    persistentVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
```
How is managed the cleaning of dfs files ? I can't find anything about this in the documentation.
Do you plan to add this feature ? Thanks
