### ISSUE TITLE
Set podSecurityContext for the dragonfly custom resource

### ISSUE THREAD

**Issue by sisrael-dn** [dragonflydb/dragonfly-operator#229]
Hello,

Right now the dragonfly crd doesn't seem to support setting any `podSecurityContext` (correct me if I'm wrong) which will pbe passed for the pods running dragonfly.
Would it it possible to add this please?

So We can create for example something like:
````
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly-sample
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly-sample
spec:
  podSecurityContext:
    capabilities:
      add: ["IPC_LOCK"]
```
