### ISSUE TITLE
Grafana Dashboard in Helm Chart doesn't work

### ISSUE THREAD

**Issue by maxpain** [dragonflydb/dragonfly-operator#256]
Hello. I've deployed the dragonfly-operator Helm chart with the following values:

```yaml
serviceMonitor:
  enabled: true

grafanaDashboard:
  enabled: true
```

But getting this error:

<img width="1876" alt="image" src="https://github.com/user-attachments/assets/c238ceec-7f2c-4485-9d8b-28a9e8e7c8e7">
