### ISSUE TITLE
Helm chart fails for Flux HelmRelease

### ISSUE THREAD

**Issue by piotrjez** [dragonflydb/dragonfly-operator#262]
Flux HelmChart can't get tags for `oci://ghcr.io/dragonflydb/dragonfly-operator/helm`, probably because those don't strictly follow the [Helm specification](https://helm.sh/docs/topics/charts/#charts-and-versioning):

Non-SemVer names are explicitly disallowed by the Flux system.
This means the v prefix is not allowed.
Happened to others before: https://github.com/fluxcd/helm-controller/issues/670, https://github.com/fluxcd/flux2/issues/3766.

Repro steps:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  type: oci
  interval: 15m
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm
---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: dragonfly-system
spec:
  chart:
    spec:
      chart: dragonfly-operator
      version: 1.1.x
      sourceRef:
        kind: HelmRepository
        name: dragonfly-operator
        namespace: flux-system
```

Output message for `flux get helmreleases -n dragonfly-system dragonfly`:
`HelmChart 'flux-system/dragonfly-system-dragonfly' is not ready: chart pull error: failed to get chart version for remote reference: could not get tags for "dragonfly-operator": unable to locate any tags in provided repository: oci://ghcr.io/dragonflydb/dragonfly-operator/helm/dragonfly-operator`

Would be nice to push charts for versions without "v" prefix or if it's not possible, there's an option to provide dual-tag policy with and without "v" prefix in versions.

**Comment by sysaeon** [comment]
@piotrjez - I'm using Flux HelmRelease and had that same error because I didn't specify the version at all. After adding that as `version: v1.1.8` it was able to pull the chart and finish deployment.

I agree the `v` should be dropped.

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: dragonfly-system
spec:
  chart:
    spec:
      chart: dragonfly-operator
      reconcileStrategy: ChartVersion
      version: v1.1.8
      sourceRef:
        kind: HelmRepository
        name: dragonfly-operator
        namespace: flux-system
  interval: 30m0s
```
