### ISSUE TITLE
Operator Fails to Reconcile StatefulSet Deletion

### ISSUE THREAD

**Issue by rezacloner1372** [dragonflydb/dragonfly-operator#285]
When manually deleting the StatefulSet managed by the Dragonfly operator, the operator does not recreate the missing StatefulSet. Instead, it logs errors and fails to reconcile. This behavior prevents the operator from restoring the expected state of the cluster, even though it should be reconciling owned resources automatically.

**Steps to Reproduce**
Deploy a Dragonfly instance using the provided CR (v1alpha1_dragonfly.yaml):
```yaml
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly-sample
  namespace: test-namespace
spec:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
    limits:
      cpu: 600m
      memory: 900Mi
```
Confirm that the StatefulSet and pods are created:
```bash
kubectl get statefulset -n test-namespace
```
Delete the StatefulSet manually:
```bash
kubectl delete statefulset dragonfly-sample -n test-namespace
```
Observe the operator logs:
```bash
kubectl logs -l app.kubernetes.io/name=dragonfly-operator -n dragonfly-operator-system
```

**Expected Behavior**
The operator should detect that the StatefulSet is missing and automatically recreate it based on the Dragonfly custom resource specification.

<img width="1435" alt="Screenshot 2025-01-13 at 13 35 02" src="https://github.com/user-attachments/assets/7f9cf851-f1f2-44c5-9dbb-de6b1bb1b423" />
