### ISSUE TITLE
The Dragonfly master does not switch when a node fails in Kubernetes.

### ISSUE THREAD

**Issue by Kirgod** [dragonflydb/dragonfly-operator#302]
**Describe the bug**
There is Dragonfly running in Kubernetes (1 master, 2 replicas).
The second time during issue with node, the master does not failover to the slave.

**To Reproduce**
1. Run dragonfly in k8s
2. Check in which node dragonfly master is running
3. Shutdown the node

**Expected behavior**
New master should be elected, if the master is unavailable.

**Environment:**
 - Workers OS: Ubuntu 22.04.4 LTS
 - Workers Kernel: 5.15.0-105-generic
 - Containerized: Kubernetes v1.29.2
 - dragonfly v1.26.2-096fde172300de91850c42dab24aa09ffee254d0
-  image: docker.dragonflydb.io/dragonflydb/operator:v1.1.9

**Reproducible Code Snippet**
```
k get po -l master
shutdown now # node where pod with master is running
# wait
k get po -l master # (no master)
```

**Additional context**
Master pod in `pending` state:
```$ k get po | grep dragonfly-foo
dragonfly-foo-0                             0/1     Pending   0                54m
dragonfly-foo-1                             1/1     Running   0                22d
dragonfly-foo-2                             1/1     Running   0                22d
```
Info from slaves:
```
root@dragonfly-foo-1:/data# redis-cli
127.0.0.1:6379> info replication
# Replication
role:slave
master_host:172.20.31.160
master_port:9999
master_link_status:down
master_last_io_seconds_ago:2809
master_sync_in_progress:0
master_replid:779aexec8fa961f6e7a431b46bb37ff4d86c41bc
slave_priority:100
slave_read_only:1

root@dragonfly-foo-2:/data# redis-cli
127.0.0.1:6379>  info replication
# Replication
role:slave
master_host:172.20.31.160
master_port:9999
master_link_status:down
master_last_io_seconds_ago:2829
master_sync_in_progress:0
master_replid:779aexec8fa961f6e7a431b46bb37ff4d86c41bc
slave_priority:100
slave_read_only:1
```
And in the pod logs just:
```
W20250311 14:38:34.344835    11 replica.cc:217] Error connecting to 172.20.31.160:9999 system:125
W20250311 14:38:35.845142    11 replica.cc:217] Error connecting to 172.20.31.160:9999 system:125
```

**Comment by eloo** [comment]
same issue here.. 

makes the "HA" setup kind of useless

**Comment by Abhra303** [comment]
Dragonfly Operator doesn't support cluster. Can you try with cluster mode off and check if you can reproduce? Also please share the operator logs here.

**Comment by Kirgod** [comment]
@Abhra303 we are not using `--cluster-mode` flag at all:
```
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  namespace: default
  labels:
    ...
  name: dragonfly-foo
spec:
  args:
    - "--dbfilename=dump"
  replicas: 3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - dragonfly-foo
        topologyKey: "kubernetes.io/hostname"
  tolerations:
    - key: "node.kubernetes.io/not-ready"
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 10
  snapshot:
    cron: "*/5 * * * *"
    persistentVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
```
