### ISSUE TITLE
maxmemory

### ISSUE THREAD

**Issue by hermanbanken** [dragonflydb/dragonfly-operator#71]
We deployed DragonflyDB using:
```yaml
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: api-proxy-dragonfly
spec:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 1Gi
```
but this is output from the pod:
<img width="1422" alt="Screenshot 2023-05-26 at 17 07 01" src="https://github.com/dragonflydb/dragonfly-operator/assets/791189/8418b4c5-9c8a-4b1c-962e-1278ee88a4f0">

This usage of 22GiB is a bit problematic, because it would OOM at 1GiB already because of the Kubernetes memory limit. Is there a way to read this maximum memory either for the operator or for the Dragonfly instance itself?
