### ISSUE TITLE
add in docs that you can specify df image version

### ISSUE THREAD

**Issue by cecchigl** [dragonflydb/dragonfly-operator#82]
It is already working, but it's not documented.
You can specify the image version of df to use in the operator like in the example above.
```
spec:
  args:
  - --dbfilename=dump
  - --save_schedule=*:10
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.8.0
  replicas: 2
  resources:
    limits:
      cpu: 600m
      memory: 750Mi
    requests:
      cpu: 500m
      memory: 500Mi
```
