### ISSUE TITLE
How to specify a namespace via Dragonfly CRD during installation

### ISSUE THREAD

**Issue by qianjunakasumi** [dragonflydb/dragonfly-operator#96]
Hello, I'm using [dragonfly-operator](https://www.dragonflydb.io/docs/getting-started/kubernetes-operator) to deploy my instance, 
I would like to be able to specify its installation namespace, this [sample yaml](https://raw.githubusercontent.com/dragonflydb/dragonfly-operator/main/config/samples/v1alpha1_dragonfly.yaml) installed dragonfly  in the default namespace.
because little experience with kubernetes and checked some documentation or search by google but couldn't find a solution, I hope to get some help

my yaml:
```
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly-instance
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly-instance
spec:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 750Mi
```

kubectl get pods -n default
```
NAME                                      READY   STATUS    RESTARTS       AGE
dragonfly-instance-0                      2/2     Running   0              30m
dragonfly-instance-1                      2/2     Running   0              22m
```

set `app.kubernetes.io/namespace: <my-namespace>` but cannot works, set `namespace` field in `spec` which is invalid value.
If need more information I appreciate to share

**Comment by Abhra303** [comment]
Hi @qianjunakasumi, first make sure the namespace exists in your cluster by running `kubectl get ns`. If not, create one by running `kubectl create namespace <your-namespace>`.

Once the namespace is created, either specify `namespace` under `metadata` in the yaml or use `-n` flag in `kubectl apply` command to specify the namespace.

Corrected yaml
```yaml
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly-instance
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly-instance
  namespace: <your-namespace>
spec:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 750Mi
```

Or via command-line:
```
kubectl apply -f <your-yaml-file> -n <your-namespace>
```

Hope this helps :)
